// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.2
// source: post_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "post_service";

export interface Post {
  id: string;
  title: string;
  description: string;
  picture: string;
  channelId: string;
}

export interface RepeatedPost {
  id: string[];
  title: string[];
  description: string[];
  picture: string[];
  channelId: string[];
}

export interface Rate {
  id: string;
  postId: string;
  parentId: string;
  reaction: string;
}

export interface CommentRate {
  id: string;
  commentId: string;
  parentId: string;
  reaction: string;
}

export interface Comment {
  id: string;
  postId: string;
  parentId: string;
  text: string;
}

export interface Boolean {
  bool: boolean;
}

export interface CreatePostRequest {
  title: string;
  description: string;
  picture: string;
  channelId: string;
}

export interface DeletePostRequest {
  id: string;
  channelId: string;
}

export interface GetPostByIdRequest {
  id: string;
}

export interface GetPostByIdResponse {
  id: string;
  title: string;
  description: string;
  picture: string;
  channelId: string;
  postComments: Comment[];
  postLikes: Rate[];
}

export interface GetAllPostsRequest {
  channelId: string;
}

export interface GetAllPostsResponse {
  posts: Post[];
}

export interface RatePostRequest {
  postId: string;
  parentId: string;
  rate: string;
}

export interface CommentPostRequest {
  postId: string;
  channelId: string;
  parentId: string;
  text: string;
}

export const POST_SERVICE_PACKAGE_NAME = "post_service";

export interface PostServiceClient {
  createPost(request: CreatePostRequest): Observable<Post>;

  getPostById(request: GetPostByIdRequest): Observable<GetPostByIdResponse>;

  getAllPosts(request: GetAllPostsRequest): Observable<GetAllPostsResponse>;

  ratePost(request: RatePostRequest): Observable<Rate>;

  commentPost(request: CommentPostRequest): Observable<Comment>;
}

export interface PostServiceController {
  createPost(request: CreatePostRequest): Promise<Post> | Observable<Post> | Post;

  getPostById(
    request: GetPostByIdRequest,
  ): Promise<GetPostByIdResponse> | Observable<GetPostByIdResponse> | GetPostByIdResponse;

  getAllPosts(
    request: GetAllPostsRequest,
  ): Promise<GetAllPostsResponse> | Observable<GetAllPostsResponse> | GetAllPostsResponse;

  ratePost(request: RatePostRequest): Promise<Rate> | Observable<Rate> | Rate;

  commentPost(request: CommentPostRequest): Promise<Comment> | Observable<Comment> | Comment;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPost", "getPostById", "getAllPosts", "ratePost", "commentPost"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POST_SERVICE_NAME = "PostService";
