// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: video_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "video_service";

export interface Video {
  id: string;
  title: string;
  description: string;
  channelId: string;
  status: string;
  previewUrl: string;
  videoUrl: string;
  createdAt: string;
  updatedAt: string;
  comments: Comment[];
  views: View[];
  likes: Like[];
}

export interface Comment {
  id: string;
  text: string;
  videoId: string;
  channelId: string;
  createdAt: string;
  updatedAt: string;
}

export interface Like {
  id: string;
  videoId: string;
  channelId: string;
  reactionType: string;
  createdAt: string;
  updatedAt: string;
}

export interface View {
  id: string;
  videoId: string;
  channelId: string;
  createdAt: string;
  updatedAt: string;
}

export interface PlaylistVideo {
  id: string;
  playlistId: string;
  videoId: string;
  position: string;
  createdAt: string;
  updatedAt: string;
}

export interface Playlist {
  id: string;
  text: string;
  channelId: string;
  createdAt: string;
  updatedAt: string;
  videos: PlaylistVideo[];
}

export interface Boolean {
  bool: boolean;
}

export interface CreateVideoRequest {
  title: string;
  description: string;
  channelId: string;
  status: string;
  previewUrl: string;
  videoUrl: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetAllVideoRequest {
  take: number;
  skip: number;
}

export interface GetAllVideoResponse {
  videos: Video[];
}

export interface GetAllChannelVideoRequest {
  channelId: string;
  take: number;
  skip: number;
}

export interface GetAllChannelVideoResponse {
  videos: Video[];
}

export interface UpdateVideoStatusRequest {
  videoId: string;
  channelId: string;
  status: string;
}

export interface CreateCommentRequest {
  text: string;
  videoId: string;
  channelId: string;
}

export interface LikeVideoRequest {
  videoId: string;
  channelId: string;
  reaction: string;
}

export interface WatchVideoRequest {
  videoId: string;
  channelId: string;
}

export interface CreatePlaylistRequest {
  text: string;
  channelId: string;
}

export interface AddVideoToPlaylistRequest {
  playlistId: string;
  videoId: string;
  position: string;
}

export interface FindVideoByIdRequest {
  videoId: string;
}

export interface FindPlaylistByIdRequest {
  id: string;
}

export const VIDEO_SERVICE_PACKAGE_NAME = "video_service";

export interface VideoServiceClient {
  createVideo(request: CreateVideoRequest): Observable<Video>;

  updateVideoStatus(request: UpdateVideoStatusRequest): Observable<Video>;

  findVideoById(request: FindVideoByIdRequest): Observable<Video>;

  getAllVideo(request: GetAllVideoRequest): Observable<GetAllVideoResponse>;

  getAllChannelVideo(request: GetAllChannelVideoRequest): Observable<GetAllChannelVideoResponse>;

  createComment(request: CreateCommentRequest): Observable<Comment>;

  likeVideo(request: LikeVideoRequest): Observable<Like>;

  watchVideo(request: WatchVideoRequest): Observable<View>;

  createPlaylist(request: CreatePlaylistRequest): Observable<Playlist>;

  addVideoToPlaylist(request: AddVideoToPlaylistRequest): Observable<Boolean>;

  findPlaylistById(request: FindPlaylistByIdRequest): Observable<Playlist>;
}

export interface VideoServiceController {
  createVideo(request: CreateVideoRequest): Promise<Video> | Observable<Video> | Video;

  updateVideoStatus(request: UpdateVideoStatusRequest): Promise<Video> | Observable<Video> | Video;

  findVideoById(request: FindVideoByIdRequest): Promise<Video> | Observable<Video> | Video;

  getAllVideo(
    request: GetAllVideoRequest,
  ): Promise<GetAllVideoResponse> | Observable<GetAllVideoResponse> | GetAllVideoResponse;

  getAllChannelVideo(
    request: GetAllChannelVideoRequest,
  ): Promise<GetAllChannelVideoResponse> | Observable<GetAllChannelVideoResponse> | GetAllChannelVideoResponse;

  createComment(request: CreateCommentRequest): Promise<Comment> | Observable<Comment> | Comment;

  likeVideo(request: LikeVideoRequest): Promise<Like> | Observable<Like> | Like;

  watchVideo(request: WatchVideoRequest): Promise<View> | Observable<View> | View;

  createPlaylist(request: CreatePlaylistRequest): Promise<Playlist> | Observable<Playlist> | Playlist;

  addVideoToPlaylist(request: AddVideoToPlaylistRequest): Promise<Boolean> | Observable<Boolean> | Boolean;

  findPlaylistById(request: FindPlaylistByIdRequest): Promise<Playlist> | Observable<Playlist> | Playlist;
}

export function VideoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createVideo",
      "updateVideoStatus",
      "findVideoById",
      "getAllVideo",
      "getAllChannelVideo",
      "createComment",
      "likeVideo",
      "watchVideo",
      "createPlaylist",
      "addVideoToPlaylist",
      "findPlaylistById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VideoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VIDEO_SERVICE_NAME = "VideoService";
