// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: auth_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user_service";

export interface Boolean {
  bool: boolean;
}

export interface UpdateUserDto {
  userId: string;
  username: string;
  email: string;
  isTwoFactorEnabled: Boolean | undefined;
}

export interface ResetPasswordDto {
  email: string;
}

export interface NewPasswordDto {
  password: string;
  token: string;
}

export interface NewVerificationRequest {
  token: string;
}

export interface Empty {
}

export interface OAuthConnectRequest {
  provider: string;
}

export interface OAuthConnectResponse {
  url: string;
}

export interface OAuthCallBackRequest {
  provider: string;
  code: string;
}

export interface FindUserByIdRequest {
  id: string;
}

export interface FindProfileRequest {
  id: string;
}

export interface RegisterDto {
  username: string;
  email: string;
  password: string;
  passwordRepeat: string;
}

export interface LoginDto {
  email: string;
  password: string;
  code?: string | undefined;
}

export interface User {
  id: string;
  username: string;
  picture: string;
  email: string;
  password: string;
  role: string;
  isVerified: boolean;
  isTwoFactorEnabled: boolean;
  method: string;
}

export const USER_SERVICE_PACKAGE_NAME = "user_service";

export interface AuthServiceClient {
  register(request: RegisterDto): Observable<User>;

  login(request: LoginDto): Observable<User>;

  findProfile(request: FindProfileRequest): Observable<User>;

  findUserById(request: FindUserByIdRequest): Observable<User>;

  updateUser(request: UpdateUserDto): Observable<User>;

  oauthcallback(request: OAuthCallBackRequest): Observable<User>;

  oauthconnect(request: OAuthConnectRequest): Observable<OAuthConnectResponse>;

  newVerification(request: NewVerificationRequest): Observable<User>;

  resetPassword(request: ResetPasswordDto): Observable<Boolean>;

  newPassword(request: NewPasswordDto): Observable<Boolean>;
}

export interface AuthServiceController {
  register(request: RegisterDto): Promise<User> | Observable<User> | User;

  login(request: LoginDto): Promise<User> | Observable<User> | User;

  findProfile(request: FindProfileRequest): Promise<User> | Observable<User> | User;

  findUserById(request: FindUserByIdRequest): Promise<User> | Observable<User> | User;

  updateUser(request: UpdateUserDto): Promise<User> | Observable<User> | User;

  oauthcallback(request: OAuthCallBackRequest): Promise<User> | Observable<User> | User;

  oauthconnect(
    request: OAuthConnectRequest,
  ): Promise<OAuthConnectResponse> | Observable<OAuthConnectResponse> | OAuthConnectResponse;

  newVerification(request: NewVerificationRequest): Promise<User> | Observable<User> | User;

  resetPassword(request: ResetPasswordDto): Promise<Boolean> | Observable<Boolean> | Boolean;

  newPassword(request: NewPasswordDto): Promise<Boolean> | Observable<Boolean> | Boolean;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "findProfile",
      "findUserById",
      "updateUser",
      "oauthcallback",
      "oauthconnect",
      "newVerification",
      "resetPassword",
      "newPassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
