// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: channel_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "channel_service";

export interface Boolean {
  bool: boolean;
}

export interface FindChannelByIdRequest {
  id: string;
}

export interface SubscribeRequest {
  userId: string;
  channelId: string;
}

export interface Subscription {
  id: string;
  channelId: string;
  userId: string;
  subscribeType: string;
}

export interface CreateChannelRequest {
  userId: string;
  name: string;
  handle: string;
  bio: string;
  profilePicture: string;
  backgroundPicture: string;
}

export interface UpdateChannelRequest {
  channelId: string;
  name: string;
  bio: string;
}

export interface Channel {
  id: string;
  userId: string;
  name: string;
  handle: string;
  bio: string;
  profilePicture: string;
  backgroundPicture: string;
}

export const CHANNEL_SERVICE_PACKAGE_NAME = "channel_service";

export interface ChannelServiceClient {
  createChannel(request: CreateChannelRequest): Observable<Channel>;

  updateChannel(request: UpdateChannelRequest): Observable<Channel>;

  findChannelById(request: FindChannelByIdRequest): Observable<Channel>;

  subscribe(request: SubscribeRequest): Observable<Subscription>;

  subscribeWithNotif(request: SubscribeRequest): Observable<Subscription>;

  unSubscribe(request: SubscribeRequest): Observable<Boolean>;
}

export interface ChannelServiceController {
  createChannel(request: CreateChannelRequest): Promise<Channel> | Observable<Channel> | Channel;

  updateChannel(request: UpdateChannelRequest): Promise<Channel> | Observable<Channel> | Channel;

  findChannelById(request: FindChannelByIdRequest): Promise<Channel> | Observable<Channel> | Channel;

  subscribe(request: SubscribeRequest): Promise<Subscription> | Observable<Subscription> | Subscription;

  subscribeWithNotif(request: SubscribeRequest): Promise<Subscription> | Observable<Subscription> | Subscription;

  unSubscribe(request: SubscribeRequest): Promise<Boolean> | Observable<Boolean> | Boolean;
}

export function ChannelServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createChannel",
      "updateChannel",
      "findChannelById",
      "subscribe",
      "subscribeWithNotif",
      "unSubscribe",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_SERVICE_NAME = "ChannelService";
