// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: post_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "post_service";

export interface Post {
  id: string;
  title: string;
  description: string;
  picture: string;
  channelId: string;
}

export interface RepeatedPost {
  id: string[];
  title: string[];
  description: string[];
  picture: string[];
  channelId: string[];
}

export interface Rate {
  id: string;
  postId: string;
  parentId: string;
  reaction: string;
}

export interface CommentRate {
  id: string;
  commentId: string;
  parentId: string;
  reaction: string;
}

export interface Comment {
  id: string;
  postId: string;
  parentId: string;
  text: string;
}

export interface Boolean {
  bool: boolean;
}

export interface CreatePostRequest {
  title: string;
  description: string;
  picture: string;
  channelId: string;
}

export interface DeletePostRequest {
  id: string;
  channelId: string;
}

export interface GetPostByIdRequest {
  id: string;
}

export interface GetAllPostsRequest {
  channelId: string;
}

export interface GetAllPostsResponse {
  posts: Post[];
}

export interface RatePostRequest {
  postId: string;
  parentId: string;
  rate: string;
}

export interface DeletePostReactionRequest {
  postId: string;
  channelId: string;
}

export interface GetAllPostReactionsRequest {
  postId: string;
}

export interface GetAllPostReactionsResponse {
  rates: Rate[];
}

export interface CommentPostRequest {
  postId: string;
  channelId: string;
  parentId: string;
  text: string;
}

export interface GetAllCommentsRequest {
  postId: string;
}

export interface GetAllCommentsResponse {
  comments: Comment[];
}

export interface GetPostCommentByIdRequest {
  id: string;
}

export interface DeletePostCommentRequest {
  commentId: string;
  channelId: string;
}

export interface RatePostCommentRequest {
  commentId: string;
  parentId: string;
  rate: string;
}

export interface DeletePostCommentReactionRequest {
  commentId: string;
  channelId: string;
}

export interface GetAllPostCommentReactionsRequest {
  commentId: string;
}

export interface GetAllPostCommentReactionsResponse {
  rates: CommentRate[];
}

export const POST_SERVICE_PACKAGE_NAME = "post_service";

export interface PostServiceClient {
  createPost(request: CreatePostRequest): Observable<Post>;

  deletePost(request: DeletePostRequest): Observable<Boolean>;

  getPostById(request: GetPostByIdRequest): Observable<Post>;

  getAllPosts(request: GetAllPostsRequest): Observable<GetAllPostsResponse>;

  ratePost(request: RatePostRequest): Observable<Rate>;

  deletePostReaction(request: DeletePostReactionRequest): Observable<Boolean>;

  getAllPostReactions(request: GetAllPostReactionsRequest): Observable<GetAllPostReactionsResponse>;

  commentPost(request: CommentPostRequest): Observable<Comment>;

  getAllComments(request: GetAllCommentsRequest): Observable<GetAllCommentsResponse>;

  getPostCommentById(request: GetPostCommentByIdRequest): Observable<Comment>;

  deletePostComment(request: DeletePostCommentRequest): Observable<Boolean>;

  ratePostComment(request: RatePostCommentRequest): Observable<CommentRate>;

  deletePostCommentReaction(request: DeletePostCommentReactionRequest): Observable<Boolean>;

  getAllPostCommentReactions(
    request: GetAllPostCommentReactionsRequest,
  ): Observable<GetAllPostCommentReactionsResponse>;
}

export interface PostServiceController {
  createPost(request: CreatePostRequest): Promise<Post> | Observable<Post> | Post;

  deletePost(request: DeletePostRequest): Promise<Boolean> | Observable<Boolean> | Boolean;

  getPostById(request: GetPostByIdRequest): Promise<Post> | Observable<Post> | Post;

  getAllPosts(
    request: GetAllPostsRequest,
  ): Promise<GetAllPostsResponse> | Observable<GetAllPostsResponse> | GetAllPostsResponse;

  ratePost(request: RatePostRequest): Promise<Rate> | Observable<Rate> | Rate;

  deletePostReaction(request: DeletePostReactionRequest): Promise<Boolean> | Observable<Boolean> | Boolean;

  getAllPostReactions(
    request: GetAllPostReactionsRequest,
  ): Promise<GetAllPostReactionsResponse> | Observable<GetAllPostReactionsResponse> | GetAllPostReactionsResponse;

  commentPost(request: CommentPostRequest): Promise<Comment> | Observable<Comment> | Comment;

  getAllComments(
    request: GetAllCommentsRequest,
  ): Promise<GetAllCommentsResponse> | Observable<GetAllCommentsResponse> | GetAllCommentsResponse;

  getPostCommentById(request: GetPostCommentByIdRequest): Promise<Comment> | Observable<Comment> | Comment;

  deletePostComment(request: DeletePostCommentRequest): Promise<Boolean> | Observable<Boolean> | Boolean;

  ratePostComment(request: RatePostCommentRequest): Promise<CommentRate> | Observable<CommentRate> | CommentRate;

  deletePostCommentReaction(
    request: DeletePostCommentReactionRequest,
  ): Promise<Boolean> | Observable<Boolean> | Boolean;

  getAllPostCommentReactions(
    request: GetAllPostCommentReactionsRequest,
  ):
    | Promise<GetAllPostCommentReactionsResponse>
    | Observable<GetAllPostCommentReactionsResponse>
    | GetAllPostCommentReactionsResponse;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createPost",
      "deletePost",
      "getPostById",
      "getAllPosts",
      "ratePost",
      "deletePostReaction",
      "getAllPostReactions",
      "commentPost",
      "getAllComments",
      "getPostCommentById",
      "deletePostComment",
      "ratePostComment",
      "deletePostCommentReaction",
      "getAllPostCommentReactions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POST_SERVICE_NAME = "PostService";
